version: "3.8"

services:
  nginx:
    container_name: nginx-inception
    image: nginx-inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure # Restart on crash
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
    - type: volume
      source: wordpress_data
      target: /var/www/html/wordpress
    networks:
      - wp-net
  wordpress:
    container_name: wordpress-inception
    image: wordpress-inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        - MYSQL_USER=$MYSQL_USER
        - MYSQL_PASSWORD=$MYSQL_PASSWORD
        - MYSQL_DB_NAME=$MYSQL_DB_NAME
    environment:
      - DOMAIN_NAME=$DOMAIN_NAME
      - WP_TITLE=$WP_TITLE
      - WP_ADMIN=$WP_ADMIN
      - WP_ADMIN_PASSWORD=$WP_ADMIN_PASSWORD
      - WP_ADMIN_EMAIL=$WP_ADMIN_EMAIL
      - WP_USER_LOGIN=$WP_USER_LOGIN
      - WP_USER_EMAIL=$WP_USER_EMAIL
      - WP_USER_PASSWORD=$WP_USER_PASSWORD
    restart: on-failure # Restart on crash
    depends_on:
      - mariadb
    volumes:
      - type: volume
        source: wordpress_data
        target: /var/www/html/wordpress
    networks:
      - wp-net
  mariadb:
    container_name: mariadb-inception
    image: mariadb-inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
        - MYSQL_USER=$MYSQL_USER
        - MYSQL_PASSWORD=$MYSQL_PASSWORD
        - MYSQL_DB_NAME=$MYSQL_DB_NAME
    restart: on-failure # Restart on crash
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wp-net

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/josesanc/data/mariadb_data
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/josesanc/data/wordpress_data

networks:
  wp-net:
    name: wp-net
