
version: "3.9"
services:
  nginx:
    build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure # Restart on crash
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - webnet
  wordpress:
    build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure # Restart on crash
    volumes:
      - wordpress_data:/var/www/html/wp-content
    depends_on:
      mariadb:
        condition: service_healthy

    networks:
      - webnet
    expose:
      - "9000"
  mariadb:
    build:
        context: ./requirements/mariadb
        dockerfile: Dockerfile
        args:
          - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
          - MYSQL_USER=$MYSQL_USER
          - MYSQL_PASSWORD=$MYSQL_PASSWORD
          - MYSQL_DB_NAME=$MYSQL_DB_NAME
    volumes:
      - mariadb_data:/var/lib/mysql
    deploy:
      restart_policy:
        condition: on-failure # Restart on crash
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - webnet
    expose:
      - "3306"

volumes:
  mariadb_data:
  wordpress_data:

networks:
  webnet:

secrets:
  certificate:
    file: ${}
  certificate_key:
    file: 